Repository Remembering-Code/ecomm-basic, pull requests merged in 2024-03, with the labels that each got.

#18 Create NavBottom Component; Style NavBottom Component at least minima…
  frontend/ecomm-frontend/src/components/NavBottom.jsx
  frontend/ecomm-frontend/src/main.tsx
Labels: enhancement

#20 created main page body content component, created top-nav component, …
  Layout_Design.epgz
  frontend/ecomm-frontend/src/App.tsx
  frontend/ecomm-frontend/src/assets/menu-bar.png
  frontend/ecomm-frontend/src/assets/menu.png
  frontend/ecomm-frontend/src/components/nav-top/TopNav.jsx
  frontend/ecomm-frontend/src/main.tsx
  frontend/ecomm-frontend/src/views/Content.jsx
  frontend/ecomm-frontend/tailwind.config.js
  package-lock.json
Labels: documentation, enhancement

#21 Delete package-lock.json from Main Body
  package-lock.json
Labels: bug

#22 remove duplicate contents from merge-conflict in 'Main.tsx'; consolid…
  frontend/ecomm-frontend/src/main.tsx
Labels: bug

#24 Create PRODUCT backend info - controller, repo, model, service;
  backend/ecomm-backend/pom.xml
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/controllers/MainController.java
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/models/Product.java
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/repositories/ProductRepo.java
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/services/ProductService.java
  backend/ecomm-backend/src/main/resources/application.properties
Labels: documentation, enhancement

#25 created navSide component, fixed naming for TopNav to NavTop, added d…
  frontend/ecomm-frontend/src/components/NavBottom.jsx
  frontend/ecomm-frontend/src/components/NavSide.jsx
  frontend/ecomm-frontend/src/components/nav-top/NavTop.jsx
  frontend/ecomm-frontend/src/views/Content.jsx
Labels: documentation, enhancement

#29 created ViewOne component, added functionality to images on the ViewO…
  frontend/ecomm-frontend/src/components/NavBottom.jsx
  frontend/ecomm-frontend/src/components/NavSide.jsx
  frontend/ecomm-frontend/src/components/nav-top/NavTop.jsx
  frontend/ecomm-frontend/src/main.tsx
  frontend/ecomm-frontend/src/views/Content.jsx
  frontend/ecomm-frontend/src/views/ViewOne.jsx
Labels: documentation, enhancement

#31 Fixed up the imports in the Java backend, updated the pom.xml with ne…
  frontend/ecomm-frontend/src/views/Content.jsx
Labels: bug

#32 Fixed up the imports in the Java backend, updated the pom.xml with ne…
  backend/ecomm-backend/pom.xml
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/controllers/MainController.java
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/models/Product.java
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/repositories/ProductRepo.java
Labels: bug

#33 Fixed up the imports in the Java backend, updated the pom.xml with ne…
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/services/ProductService.java
Labels: bug

#34 added CORS config package/class to backend; minor POM xml changes for…
  backend/ecomm-backend/pom.xml
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/config/CorsConfig.java
  frontend/ecomm-frontend/src/main.tsx
  frontend/ecomm-frontend/src/views/Test.jsx
Labels: bug, enhancement

#36 fixed pom dependencies, switched out dummydata with actual data from …
  Layout_Design.epgz
  backend/ecomm-backend/pom.xml
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/models/Product.java
  backend/ecomm-backend/src/main/java/com/rc/ecommbackend/repositories/ProductRepo.java
  backend/ecomm-backend/src/main/resources/application.properties
  frontend/ecomm-frontend/src/components/nav-top/NavTop.jsx
  frontend/ecomm-frontend/src/main.tsx
  frontend/ecomm-frontend/src/views/Content.jsx
  frontend/ecomm-frontend/src/views/Test.jsx
  frontend/ecomm-frontend/src/views/ViewOne.jsx
Labels: documentation, enhancement
